services:
  - type: web
    name: electrofix-api
    env: node
    region: singapore
    rootDir: ElectroFix-API
    buildCommand: npm install --production=false && npm run build && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_h60QMTJHpEri@ep-mute-glitter-apxia23e.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        value: electrofix_secret_key
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
